sudo: false
language: go
go:
  - 1.10.x
  - 1.11.x
  - master
os: linux
install:
  - go get -t -v ./...

script:
  - go test -v -race ./...

matrix:
  allow_failures:
    - go: master
  fast_finish: true
